# Configuración inicial 

# Paquetes

library(readxl)
library(phyloseq)
library(vegan)
library(tidyverse)
library(microbiome)
library(MetBrewer)
library(showtext)
library(microbiomeutilities)
library(MicrobeR)
library(ade4)
library(CCA)
library(correlation)
library(eulerr)
library(ggpubr)
library(ggsci)
library(gt)
library(gtable)
library(gtExtras)
library(patchwork)
library(qiime2R)
library(gtsummary)
library(ggfortify)
library(ANCOMBC)
library(DESeq2)
library(MoMAColors)
library(pheatmap)
library(microeco)
library(file2meco)
font_add_google("Rubik","Rubik")
font.families()
showtext_auto()
options(encoding = "UTF-8")
Sys.setlocale("LC_ALL", "German")
